CREATE TABLE spring_session
(
    primary_id            CHAR(36)     NOT NULL PRIMARY KEY,
    session_id            CHAR(36)     NOT NULL UNIQUE,
    creation_time         BIGINT       NOT NULL,
    last_access_time      BIGINT       NOT NULL,
    max_inactive_interval INTEGER      NOT NULL,
    expiry_time           BIGINT       NOT NULL,
    principal_name        VARCHAR(100)
);

CREATE INDEX spring_session_ix2 ON spring_session (expiry_time);
CREATE INDEX spring_session_ix3 ON spring_session (principal_name);

CREATE TABLE spring_session_attributes
(
    session_primary_id CHAR(36)     NOT NULL REFERENCES spring_session (primary_id) ON DELETE CASCADE,
    attribute_name     VARCHAR(200) NOT NULL,
    attribute_bytes    BYTEA        NOT NULL,
    PRIMARY KEY (session_primary_id, attribute_name)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) CHECK (role IN ('USER', 'ADMIN')),
    enabled  BOOLEAN      NOT NULL
);

CREATE TABLE verification_codes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(255)                            NOT NULL,
    user_id     BIGINT,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_verification_codes PRIMARY KEY (id)
);

ALTER TABLE verification_codes
    ADD CONSTRAINT uc_verification_codes_user UNIQUE (user_id);

ALTER TABLE verification_codes
    ADD CONSTRAINT FK_VERIFICATION_CODES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);