CREATE TABLE products
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    ean           VARCHAR(255),
    manufacturer  VARCHAR(255),
    quantity      FLOAT                                   NOT NULL,
    quantity_unit VARCHAR(255)                            NOT NULL,
    nutrient_unit VARCHAR(255)                            NOT NULL,
    density       FLOAT                                   NOT NULL,
    energy_kcal   FLOAT                                   NOT NULL,
    fat           FLOAT,
    saturated_fat FLOAT,
    carbohydrates FLOAT,
    sugars        FLOAT,
    fiber         FLOAT,
    protein       FLOAT,
    salt          FLOAT,
    price         DECIMAL(10, 2),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_products PRIMARY KEY (id)
);