CREATE TABLE ingredients
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity   FLOAT                                   NOT NULL,
    unit       VARCHAR(255)                            NOT NULL,
    recipe_id  BIGINT,
    product_id BIGINT,
    CONSTRAINT pk_ingredients PRIMARY KEY (id)
);

CREATE TABLE recipes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    user_id     BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_recipes PRIMARY KEY (id)
);

ALTER TABLE products
    ADD recipe_id BIGINT;

ALTER TABLE products
    ADD CONSTRAINT uc_products_recipe UNIQUE (recipe_id);

ALTER TABLE ingredients
    ADD CONSTRAINT FK_INGREDIENTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE ingredients
    ADD CONSTRAINT FK_INGREDIENTS_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipes (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipes (id);

ALTER TABLE recipes
    ADD CONSTRAINT FK_RECIPES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE products
    ALTER COLUMN carbohydrates SET NOT NULL;

ALTER TABLE products
    ALTER COLUMN fat SET NOT NULL;

ALTER TABLE products
    ALTER COLUMN protein SET NOT NULL;